config/routes.rb
Rails.application.routes.draw do
  resources :exchanges
  resources :incomes
  resources :records
  resources :expenditures
  resources :projects
  resources :events
  resources :orders do
    collection do
      get 'canceled'
      get 'executed'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get 'order_file/:id', to: 'orders#download_file', as: 'order_file'
  delete 'order_file/:id', to: 'orders#delete_file'
  get 'record_file/:id', to: 'records#download_file', as: 'record_file'
  delete 'record_file/:id', to: 'records#delete_file'
  get 'exchange_file/:id', to: 'exchanges#download_file', as: 'exchange_file'
  delete 'exchange_file/:id', to: 'exchanges#delete_file'

  root to: 'orders#index'
  devise_for :users
  resources :users
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  before_action :check_editors, except: [:show, :index]
  before_action :check_viewers, only: [:show, :index]

  def index
    @incomes = Income.all
  end

  def show
  end

  def new
    @income = Income.new
  end

  def edit
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      flash[:notice] = t(:income_source_was_created)
      redirect_to @income
    else
      render :new
    end
  end

  def update
    if @income.update(income_params)
      flash[:notice] = t(:income_source_was_updated)
      redirect_to @income
    else
      render :edit
    end
  end

  def destroy
    if @income.destroy
      flash[:notice] = t(:income_source_was_deleted)
      redirect_to incomes_path
    else
      flash[:notice] = t(:income_source_was_not_deleted)
      redirect_to root_path
    end
  end

  private
    def set_income
      @income = Income.find(params[:id])
    end

    def check_editors
      if !cfo_treasurer_case?
        flash[:error] = t(:not_allowed)
        redirect_to root_path
      end
    end

    def check_viewers
      if !can_see_as_auditor_cfo_treasurer?
        flash[:error] = t(:not_allowed)
        redirect_to root_path
      end
    end

    def income_params
      params.require(:income).permit(:name, :project_id, :description)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
  def options_for_income_project
    Project.all.collect { |p| [p.name, p.id] }
  end
end

app/views/incomes/_form.html.slim
- if not @income.blank?
  = form_for @income do |f|
    - if @income.errors.any?
      #error_explanation
        h2 = "#{t(:you_have_errors)}: #{@income.errors.count}"
        ul
          - @income.errors.full_messages.each do |message|
            li = message
    .form-group
      = f.label :name, t(:income_source_name)
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :project_id, t(:income_project)
      = f.select :project_id, options_for_income_project,                      \
                              { include_blank: true },                         \
                              { class: 'form-control' }
    .form-group
      = f.label :description, t(:income_source_description)
      = f.text_area :description, class: 'form-control'
    = f.submit t(:accept), class: 'btn btn-primary'

app/views/incomes/edit.html.slim
- if not @income.blank?
  h1 = t(:editing_income_source)

  == render 'form'
  br
  = link_to t(:show), @income
  = " | "
  = link_to t(:back), incomes_path

app/views/incomes/index.html.slim
- content_for :main_title do
  div class='main-title-content'
    = t(:income_sources)
- if cfo_treasurer_case?
  = link_to new_income_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    = t(:new_income_source)
  br
  br

.table-responsive
  table.table.table-striped.table-bordered.table-hover#income-sources-table.no_scroll
    thead
      tr
        th
          = t(:income_source_name)
        th
          = t(:income_source_description)
        th
          = t(:income_project)
        - if cfo_treasurer_case?
          th
          th
    tbody
      - @incomes.each do | income |
        tr
          td.min-width
            = show_source(income.name, income_path(income.id))
          td
            = income.description
          td
            = income.project.try(:name)
          - if cfo_treasurer_case?
            td
              = link_to t(:edit), edit_income_path(income) 
            td
              = link_to t(:delete), income, method: :delete, data: { confirm: t(:delete_confirmation) }
script

  |$('#income-sources-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1});

app/views/incomes/new.html.slim
h1 = t(:new_income_source)

== render 'form'
br
= link_to t(:back), incomes_path

app/views/incomes/show.html.slim
- if not @income.blank?
  .panel.panel-default
    .panel-heading
      h3.panel-title
        b = t(:income_source)
    .panel-body
      dl
        dt
          = t(:income_source_name)
        br
        dd
          = @income.name
        br
        dt
          = t(:income_project)
        br
        dd
          = @income.project.try(:name)
        br
        dt
          = t(:income_source_description)
        br
        dd
          = @income.description
        br
        = link_to t(:income_sources), incomes_path
        = ' | '
        = link_to t(:journal), records_path

        - if cfo_treasurer_case?
          = ' | '
          = link_to t(:edit), edit_income_path(@income)