config/routes.rb
Rails.application.routes.draw do
  resources :exchanges
  resources :incomes
  resources :records
  resources :expenditures
  resources :projects
  resources :events
  resources :orders do
    collection do
      get 'canceled'
      get 'executed'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get 'order_file/:id', to: 'orders#download_file', as: 'order_file'
  delete 'order_file/:id', to: 'orders#delete_file'
  get 'record_file/:id', to: 'records#download_file', as: 'record_file'
  delete 'record_file/:id', to: 'records#delete_file'
  get 'exchange_file/:id', to: 'exchanges#download_file', as: 'exchange_file'
  delete 'exchange_file/:id', to: 'exchanges#delete_file'

  root to: 'orders#index'
  devise_for :users
  resources :users
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper

  before_action :set_order, only: [:show, :edit, :update]

  def download_file
    if @file = OrderFile.find_by('id = ?', params[:id]) # ok
      @order = @file.order
      if @order && can_he_see?(@order)
        path = @file.path
        send_file Rails.root.to_s + path, x_sendfile: true if path
      else
        flash[:alert] = t(:no_file)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:no_file)
      redirect_to root_path
    end
  end

  def delete_file
    if @file = OrderFile.find_by('id = ?', params[:id]) # ok
      @order = @file.order
      if can_he_edit?(@order) && @file.destroy
        flash[:notice] = t(:file_was_deleted)
        redirect_to edit_order_path(@order.id)
      else
        flash[:notice] = t(:file_was_not_deleted)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:no_file)
      redirect_to root_path
    end
  end

  def index
    @title = t(:current_orders)
    @state1 = Order.states[:executed]
    @state2 = Order.states[:canceled]
    @state3 = Order.states[:approval]
    if current_user.user?
      @orders_part_1 = current_user.permitted_orders.where
                                   .not("state = ? or state = ?", @state1,
                                                                  @state2)
      @orders_part_2 = current_user.orders.where.not("state = ? or state = ?",
                                                     @state1,
                                                     @state2)
      @orders = @orders_part_1 + @orders_part_2
    elsif current_user.cfo? && !cfo_treasurer_case?
      @orders_part_1 = current_user.permitted_orders.where
                                   .not("state = ? or state = ? or state = ?",
                                        @state1,
                                        @state2,
                                        @state3)
      @orders_part_2 = current_user.orders.where
                                   .not("state = ? or state = ? or state = ?",
                                        @state1,
                                        @state2,
                                        @state3)
      @orders_part_3 = Order.where("state = ?", @state3)

      @orders = @orders_part_1 + @orders_part_2 + @orders_part_3
    elsif cfo_treasurer_case?
      @orders = Order.where.not("state = ? or state = ?", @state1, @state2)
    elsif current_user.auditor?
      @orders = Order.where.not("state = ? or state = ?", @state1, @state2)
    elsif current_user.admin?
      @orders = []
    end
  end

  def canceled
    @title = t(:canceled_orders)
    @state = Order.states[:canceled]
    if current_user.user? || (current_user.cfo? && !cfo_treasurer_case?)
      @orders_part_1 = current_user.permitted_orders.where(state: @state)
      @orders_part_2 = current_user.orders.where(state: @state)
      @orders = @orders_part_1 + @orders_part_2
    elsif cfo_treasurer_case?
      @orders = Order.where(state: @state)
    elsif current_user.auditor?
      @orders = Order.where(state: @state)
    elsif current_user.admin?
      @orders = []
    end
    render 'orders/index'
  end

  def executed
    @title = t(:executed_orders)
    @state = Order.states[:executed]
    if current_user.user? || (current_user.cfo? && !cfo_treasurer_case?)
      @orders_part_1 = current_user.permitted_orders.where(state: @state)
      @orders_part_2 = current_user.orders.where(state: @state)
      @orders = @orders_part_1 + @orders_part_2
    elsif cfo_treasurer_case?
      @orders = Order.where(state: @state)
    elsif current_user.auditor?
      @orders = Order.where(state: @state)
    elsif current_user.admin?
      @orders = []
    end
    render 'orders/index'
  end

  def show
    if can_he_see?(@order)
      render 'show'
    else
      flash[:error] = t(:not_allowed)
      redirect_to orders_path
    end
  end

  def new
    @order = Order.new user: current_user
  end

  def edit
    if can_he_edit?(@order)
      render 'edit'
    else
      flash[:error] = t(:not_allowed)
      redirect_to orders_path
    end
  end

  def create
    if !current_user.admin?
      @order = Order.new(order_params)
      @order.user = current_user
      @order.state = 'preparation'

      if @order.save
        files = params[:order][:files]
        dir = "private/files/orders/order_#{@order.id}/"
        handle_files(@order, :order_files, files, dir) if files
        flash[:notice] = t(:order_was_created)
        redirect_to @order
      else
        render :new
      end
    else
      redirect_to root_path
    end
  end

  def update
    # Users can change order states
    if params[:commit] && params[:order] && !params[:order][:state].blank?
      newstate = params[:order][:state]
      verificator_id = params[:order][:user]
      note = params[:order][:note]

      result = @order.changestate(newstate, current_user.id, verificator_id,
                                                             note)
      if !result.blank?
        flash[:error] = result
      else
        flash[:message] = t(:state_was_changed)
      end
      redirect_to orders_path and return
      # redirect_to :back and return
    end

    # Treasurer can add order to journal
    if params[:to_journal] && cfo_treasurer_case?
      if @order = Order.find_by(id: params[:to_journal])
        @order.send_to_journal
        flash[:notice] = t(:order_was_sent)
        redirect_to executed_orders_path and return
      end
    end

    # Order owner can withdraw it in verification state
    if params[:withdraw]
      if @order = Order.find_by(id: params[:withdraw])
        if @order.author?(current_user.id) && @order.withdraw
          flash[:notice] = t(:order_was_withdrawn)
          redirect_to orders_path and return
        end
      end
    end

    # Order owner can update his order in 'preparation' state
    if params[:order] && can_he_edit_as_author?(@order)
      if @order.update(order_params)
        files = params[:order][:files]
        dir = "private/files/orders/order_#{@order.id}/"
        handle_files(@order, :order_files, files, dir) if files
        flash[:notice] = t(:order_was_updated)
        redirect_to @order
      else
        render :edit
      end

    # CFO and Treasurer can update specific parts of orders
    # (project_id, ccy, amount) in 'approval', 'execution' and 'executed' states
    elsif params[:order] && special_access_for_cfo_or_treasurer?(@order.state)
      @order.project_id = params[:order][:project_id]
      @order.expenditure_id = params[:order][:expenditure_id]
      @order.ccy = params[:order][:ccy]
      @order.amount = params[:order][:amount]
      @order.handled = params[:order][:handled]
      if @order.save
        @order.log_it(current_user.id)
        files = params[:order][:files]
        dir = "private/files/orders/order_#{@order.id}/"
        handle_files(@order, :order_files, files, dir) if files
        flash[:notice] = t(:order_was_updated)
        redirect_to @order
      else
        render :edit
      end
    else
      flash[:error] = t(:not_allowed)
      redirect_to root_path
    end
  end

  def destroy
    if 1 == 2
      @order.destroy
      flash[:notice] = t(:order_was_deleted)
    end
    redirect_to orders_path
  end

  private
    def set_order
      if !(@order = Order.find_by(id: params[:id]))
        redirect_to orders_path
      end
    end

    def order_params
      params.require(:order).permit(:subject, :amount, :ccy, :expenditure_id,
                                                             :project_id,
                                                             :files)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def allowed_states(order)
    order_user_id = order.user_id
    sent_to = order.sent_to
    current_state = order.state
    @allowed_states = [current_state]

    case current_state
    when "preparation"
      if current_user.id == order_user_id
        @allowed_states = [current_state] | ["verification", "approval", "canceled"]
      else
        @allowed_states = [current_state]
      end
    when "verification"
      if current_user.user? && sent_to == current_user.id
        @allowed_states = [current_state, "preparation", "approval", "canceled"]
      else
        @allowed_states = [current_state]
      end
    when "approval"
      if current_user.cfo? && cfo_treasurer_case?
        @allowed_states = [current_state] | ["preparation", "executed", "canceled"]
      elsif current_user.cfo?
        @allowed_states = [current_state] | ["preparation", "execution", "canceled"]
      else
        @allowed_states = [current_state]
      end
    when "execution"
      if cfo_treasurer_case?
        @allowed_states = [current_state] | ["canceled", "executed"]
      else
        @allowed_states = [current_state]
      end
    when "canceled"
      @allowed_states = [current_state]
    when "executed"
      @allowed_states = [current_state]
    end
  end

  def show_sender(order)
    if order.verification?
      " (" + (order.recipient.try(:name) || order.recipient.try(:email)) + ") "
    end
  end

  def users_for_verification
    accepted_users = User.where
                         .not("id = ? or role = ? or role = ? or role = ? " +
                              "or role = ?",
                              current_user.id,
                              User.roles[:cfo],
                              User.roles[:treasurer],
                              User.roles[:auditor],
                              User.roles[:admin])
    accepted_users.map{ |u| [u.name, u.id] } rescue ""
  end

  def set_order_color?(order)
    set_color = false
    if order.executed?
      paid_amount = Record.expenditure.where(source_id: order.id)
                                      .group(:ccy).sum(:amount)
      if !(paid_amount[Order.ccys[order.ccy]] == -order.amount &&
           paid_amount.count == 1) && !order.handled?
        set_color = true
      end
    end
    return set_color
  end

  def amount_checker_state(state)
    state ? t(:amount_checker_disabled) : t(:amount_checker_enabled)
  end

  def set_length(text)
    truncate(text, length: 117)
  end

  def order_get_records(order)
    records = order.try(:records)
    if records.blank?
      return nil
    else
      return records
    end
  end

end

app/views/orders/_copy_button.html.slim
- if order
  hr.hr-small
  textarea id="copy_#{order.id}_text" class="hidden-text"
    = order.subject
  div.text-right
    = button_tag type: 'button', id: "copy_#{order.id}",
                                  class: "btn btn-xs btn-primary copy-button" do
      span.glyphicon.glyphicon-copy.copy-button-glyphicon aria-hidden="true"

app/views/orders/_form.html.slim
- if not @order.blank?
    = form_for @order do |f|
      - if @order.errors.any?
        #error_explanation
          h2 = "#{t(:you_have_errors)}: #{@order.errors.count}"
          ul
            - @order.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :subject, t(:subject)
        = f.text_area :subject, class: 'form-control', rows: 6
      .form-group
        = f.label :ccy, t(:ccy)
        = f.select :ccy, Order.ccys.keys.map{ |ccy| [ccy, ccy] }, {}, { class: 'form-control' }
      .form-group
        = f.label :amount, t(:amount)
        = f.number_field :amount, class: 'form-control'
      .form-group
        = f.label :project_id, t(:related_project)
        = f.select :project_id, Project.all.collect { |project| [project.name, project.id] }, { include_blank: true }, { class: 'form-control' }
      .form-group
        = f.label :expenditure_id, t(:related_expenditure)
        = f.select :expenditure_id, Expenditure.all.collect { |expenditure| [expenditure.name, expenditure.id] }, { include_blank: true }, { class: 'form-control' }
      .form-group
        = f.label :files, t(:files)
        = f.file_field :files, id: "files", multiple: true
        p class="help-block"
          = t(:files_prompt)
      - if controller.action_name == 'edit'
        = files_to_delete(@order, :order_files, :order_file_path)

      = f.submit t(:accept), class: 'btn btn-primary'

app/views/orders/_form2.html.slim
- if not @order.blank?
    = form_for @order do |f|
      - if @order.errors.any?
        #error_explanation
          h2 = "#{t(:you_have_errors)}: #{@order.errors.count}"
          ul
            - @order.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :subject, t(:subject)
        = f.text_area :subject, class: 'form-control', rows: 6, disabled: true
      .form-group
        = f.label :ccy, t(:ccy)
        = f.select :ccy, Order.ccys.keys.map{ |ccy| [ccy, ccy] }, {}, { class: 'form-control' }
      .form-group
        = f.label :amount, t(:amount)
        = f.number_field :amount, class: 'form-control'
      .form-group
        = f.label :project_id, t(:related_project)
        = f.select :project_id, Project.all.collect { |project| [project.name, project.id] }, { include_blank: true }, { class: 'form-control' }
      .form-group
        = f.label :expenditure_id, t(:related_expenditure)
        = f.select :expenditure_id, Expenditure.all.collect { |expenditure| [expenditure.name, expenditure.id] }, { include_blank: true }, { class: 'form-control' }
      .form-group
        = f.label :files, t(:files)
        = f.file_field :files, id: "files", multiple: true
        p class="help-block"
          = t(:files_prompt)
      - if controller.action_name == 'edit'
        = files_to_delete(@order, :order_files, :order_file_path)

      - if @order.executed?
        .checkbox
          label
            = f.check_box :handled
            = t(:handled)

      = f.submit t(:accept), class: 'btn btn-primary'

app/views/orders/_order_payments.html.slim
- if records
  div class='order-payments-wrapper'
    div class='order-payments-header'
      = t(:order_payments)
    div class='order-payments-body'
      .table-responsive
        table.table.table-striped.table-bordered.table-hover
          thead
            tr
              th
                = t(:record_date)
              th
                = t(:ccy)
              th
                = t(:amount)
          tbody
            - records.each do | record |
              tr
                td
                  = set_date(record.date, record_path(record.id))
                td
                  = record.ccy
                - if record.amount >= 0
                  td.plus.text-right.no_wrap
                    = number_to_currency(record.amount, unit: '', precision: 0)
                - else
                  td.text-right.no_wrap
                    = number_to_currency(record.amount, unit: '', precision: 0)

app/views/orders/edit.html.slim
- if not @order.blank?
  h1 = t(:editing_order)

  - if special_access_for_cfo_or_treasurer? @order.state
    == render 'form2'
  - else
    == render 'form'
  br
  = link_to t(:show), @order
  = " | "
  - if @order.executed?
    = link_to t(:executed_orders), executed_orders_path
  - elsif @order.canceled?
    = link_to t(:canceled_orders), canceled_orders_path
  - else
    = link_to t(:current_orders), orders_path

script

  | $("#files").on("change", handle);
  | function handle() {
  |   var $files = $('#files')[0].files;
  |   for (i = 0; i < $files.length; i++) {
  |     if ($files[i].size > 2097152) {
  |       alert("#{t(:max_file_size)}");
  |       $('#files').val('');
  |       return;
  |     }
  |   }
  | };

app/views/orders/index.html.slim
- content_for :main_title do
  div class='main-title-content'
    = @title
= link_to new_order_path, class: 'btn btn-primary' do 
  span.glyphicon.glyphicon-plus
  = t(:new_order)
br
br
.table-responsive
  table.table.table-striped.table-bordered.table-hover#order-table.no_scroll
    thead
      tr
        th
          = t(:created_at)
        th
          = t(:purpose)
        th
          = t(:ccy)
        th
          = t(:amount)
        th
          = t(:initiator)
        th
          = t(:state)
        - if cfo_or_treasurer?
          th
            = t(:project)
          th
            = t(:expenditure)
        - if controller.action_name == 'executed' && cfo_or_treasurer?
          th.small-width
        - if controller.action_name == 'index' || current_user &&              \
              controller.action_name == 'executed' && cfo_treasurer_case?
          th
    tbody
      - @orders.each do | order |
        tr
          td data-order="#{order.created_at}"
            = set_date(order.created_at, order_path(order.id))
          - if set_order_color?(order)
            td.awaiting
              = set_length(order.subject)
              - if cfo_treasurer_case?
                = render partial: 'copy_button', locals: { order: order }
          - else
            td
              = set_length(order.subject)
              - if cfo_treasurer_case?
                = render partial: 'copy_button', locals: { order: order }
          td
            = order.ccy
          td.text-right.no_wrap
            = number_to_currency(order.amount, unit: '', precision: 0)
          td
            = order.user.try(:name)
          td
            - if allowed_states(order).size > 1
              = select_tag(:state,                                             \
                options_for_select(                                            \
                  allowed_states(order),                                       \
                  selected: order.state),                                      \
                  { id: "select_" + order.id.to_s,                             \
                    onchange: 'showfields("' + (order.state) + '", "' + order.id.to_s + '")' })
            - else
              .order_state
                = order.state
            small
              = show_sender(order)
            = select_tag(:user,                                                \
                        options_for_select(users_for_verification),            \
                        { id: "user_" + order.id.to_s,                         \
                          style: "display: none;",                             \
                          prompt: t(:recipient_field) })
          - if cfo_or_treasurer?
            td
              = order.project.try(:name)
            td
              = order.expenditure.try(:name)
          - if controller.action_name == 'executed' && cfo_or_treasurer?
            - if order.handled?
              td.small-width.red-asterisk
                = '*'
            - else
              td.small-width.green-plus
                = '+'

          - if controller.action_name == 'index' || current_user &&            \
                controller.action_name == 'executed' && cfo_treasurer_case?
            td.text-center
              = link_to t(:edit), edit_order_path(order) if can_he_edit? order
              - if order.verification? && order.author?(current_user.id)
                = link_to t(:withdraw),                                        \
                          order_path(order.id, withdraw: order.id),            \
                          method: :put


              - if cfo_treasurer_case? && controller.action_name == 'executed'
                hr.small-margin
                = link_to t(:send_to_journal),                                 \
                          order_path(order.id, to_journal: order.id),          \
                          method: :put

/ Modal
div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModal2Label"
  div class="modal-dialog" role="document"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
            |&times;
        h4 class="modal-title" id="modalSelectState"

      div class="modal-body text-center" id="Modal2body"

        form id="modalOrderForm" accept-charset="UTF-8" method="post"
          input name="utf8" type="hidden" value="✓"
          input type="hidden" name="_method" value="patch"
          input type="hidden" name="authenticity_token"

          div id='modalQuestion'

          input id="modalSelectStateInput" type='hidden' name='order[state]'

          div class="form-group" id="modalSelectUser"

          div class="form-group" id="orderNote"
            label for="order_note"
              = t(:note)
            textarea id="order_note" placeholder="#{t(:note_must_be_present)}" name='order[note]' class='form-control' rows='6'

          div class="text-right"
            input type='submit' name='commit' value="#{t(:save)}" class='btn btn-primary'
            = "   "
            button type="button" class="btn btn-default" data-dismiss="modal" id='big_nope'
              = t(:cancel)
      div class="modal-footer" id="Modal2footer"

script
  | $('#order-table').on('click', function(e){ toClipboard(e); });
  |
  | function createModal(s, new_state, current_state, translation) {
  |   if (current_state != '') {
  |     $('#select_' + s).val(current_state);
  |   } else {
  |     $('#select_' + s).val('preparation');
  |   }
  |   $('#orderNote').show();
  |   $('#modalQuestion').empty();
  |   $('#modalSelectState').empty();
  |   $('#order_note').val("");
  |   $('#modalOrderForm').attr('action', '#{orders_path}' + '/' + s);
  |   $('#modalSelectState').append(translation);
  |   $('#modalSelectStateInput').val(new_state);
  |   if (new_state == 'verification') {
  |     $('#modalSelectUser').empty().append("<label for='modalUsers'>#{t(:recipient)}</label>");
  |     $('#modalSelectUser').append("<select class='form-control' id='modalUsers' name='order[user]'>");
  |     var $user_options = $('#user_' + s + ' > option').clone();
  |     $('#modalUsers').append($user_options);
  |   } else {
  |     $('#modalSelectUser').empty();
  |   }
  |   if (new_state == 'approval' || new_state == 'executed' || new_state == 'execution') {
  |
  |     $('#orderNote').hide();
  |     $('#modalQuestion').append("<h3>#{t(:change_state)}</h3><br>");
  |   }
  |   $('#myModal2').modal('show');
  | }

  | function showfields(current_state, s) { 
  |   $('#user_' + s).hide();
  |   switch ($('#select_' + s).val()) {
  |     case current_state:
  |       $('#flash').hide();
  |       break;
  |     case "preparation":
  |       createModal(s, 'preparation', current_state, '#{t(:preparation)}');
  |       break;
  |     case "verification": 
  |       createModal(s, 'verification', current_state, '#{t(:verification)}');
  |       break;
  |     case "canceled":
  |       createModal(s, 'canceled', current_state, '#{t(:canceled)}');
  |       break;
  |     case "approval":
  |       createModal(s, 'approval', current_state, '#{t(:approval)}');
  |       break;
  |     case "execution":
  |       createModal(s, 'execution', current_state, '#{t(:execution)}');
  |       break; 
  |     case "executed":
  |       createModal(s, 'executed', current_state, '#{t(:executed)}');
  |       break;
  |     default:
  |       $('#user_' + s).hide();
  |   }
  /|     console.log('#save_' + s);
  /|     console.log('this.val' + $(this).val());      
  | }

  |$('#order-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1})

app/views/orders/new.html.slim
h1 = t(:new_order)

== render 'form'
br
= link_to t(:back), orders_path

script

  | $("#files").on("change", handle);
  | function handle() {
  |   var $files = $('#files')[0].files;
  |   for (i = 0; i < $files.length; i++) {
  |     if ($files[i].size > 2097152) {
  |       alert("#{t(:max_file_size)}");
  |       $('#files').val('');
  |       return;
  |     }
  |   }
  | };

app/views/orders/show.html.slim
/  p#notice = notice
- if not @order.blank?
  .panel.panel-default
    .panel-heading
      h3.panel-title
        b = t(:order)
    .panel-body
      dl
        dt
          = t(:subject)
        br
        dd
          = @order.subject
        br
        dt
          = t(:project)
        br
        dd
          = @order.project.try(:name) or t(:no_project)
        br
        dt
          = t(:expenditure)
        br
        dd
          = @order.expenditure.try(:name) or t(:no_expenditure)
        br
        dt
          = t(:amount)
        br
        dd
          = "#{number_to_currency(@order.amount, unit: '',                     \
                                                 precision: 0)} #{@order.ccy}"
        br
        dt
          = t(:attached_files)
        br
        dd
          = show_files(@order, :order_files, :order_file_path)
        br
        - if @order.executed? && can_see_as_auditor_cfo_treasurer?
          dt
            = t(:amount_checker)
          br
          dd
            = amount_checker_state(@order.handled?)
          br
        - if records = order_get_records(@order)
          = render partial: 'order_payments', locals: { records: records }
        - else
          dt
            = t(:order_payments)
          br
          dd
            = t(:no_order_payments)
          br
        - if @order.executed?
          = link_to t(:executed_orders), executed_orders_path
        - elsif @order.canceled?
          = link_to t(:canceled_orders), canceled_orders_path
        - else
          = link_to t(:current_orders), orders_path

        - if can_see_as_auditor_cfo_treasurer?
          = ' | '
          = link_to t(:journal), records_path

        - if can_he_edit? @order
          = ' | '
          = link_to t(:edit), edit_order_path(@order)

  - if not @order.events.blank? 
    .table-responsive
      table.table.table-striped.table-bordered.table-hover
        thead
          tr
            th.text-center
              = t(:state)
            th.text-center
              = t(:user_name)
            th.text-center
              = t(:created_at)
            th.text-center
              = t(:note)
        tbody
          tr
            td
              = :preparation rescue "Can't get it"
            td
              = @order.user.name rescue "Can't get it"
            td
              = @order.created_at.localtime                                    \
                      .strftime("%d.%m.%Y %H:%M:%S") rescue "Can't get it"
            td
              = ""
          - @order.events.order('created_at').each do |event|
            tr
              td
                = event.state rescue "Can't get it"
              td
                = event.user.name rescue "Can't get it"
              td
                = event.created_at.localtime                                   \
                        .strftime("%d.%m.%Y %H:%M:%S") rescue "Can't get it"
              td
                = event.note rescue "Can't get it"