config/routes.rb
Rails.application.routes.draw do
  resources :exchanges
  resources :incomes
  resources :records
  resources :expenditures
  resources :projects
  resources :events
  resources :orders do
    collection do
      get 'canceled'
      get 'executed'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get 'order_file/:id', to: 'orders#download_file', as: 'order_file'
  delete 'order_file/:id', to: 'orders#delete_file'
  get 'record_file/:id', to: 'records#download_file', as: 'record_file'
  delete 'record_file/:id', to: 'records#delete_file'
  get 'exchange_file/:id', to: 'exchanges#download_file', as: 'exchange_file'
  delete 'exchange_file/:id', to: 'exchanges#delete_file'

  root to: 'orders#index'
  devise_for :users
  resources :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :orders
  validates :name, presence: true
  #  validates :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :check_editors, except: [:show, :index]
  before_action :check_viewers, only: [:show, :index]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = t(:project_was_created)
      redirect_to @project
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = t(:project_was_updated)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = t(:project_was_deleted)
      redirect_to projects_path
    else
      flash[:notice] = t(:project_was_not_deleted)
      redirect_to root_path
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def check_editors
      if !cfo_treasurer_case?
        flash[:error] = t(:not_allowed)
        redirect_to root_path
      end
    end

    def check_viewers
      if !can_see_as_auditor_cfo_treasurer?
        flash[:error] = t(:not_allowed)
        redirect_to root_path
      end
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
- if not @project.blank?
  = form_for @project do |f|
    - if @project.errors.any?
      #error_explanation
        h2 = "#{t(:you_have_errors)}: #{@project.errors.count}"
        ul
          - @project.errors.full_messages.each do |message|
            li = message
    .form-group
      = f.label :name, t(:project_name)
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :description, t(:project_description)
      = f.text_area :description, class: 'form-control'
    = f.submit t(:accept), class: 'btn btn-primary'

app/views/projects/edit.html.slim
- if not @project.blank?
  h1 = t(:editing_project)

  == render 'form'
  br
  = link_to t(:show), @project
  = " | "
  = link_to t(:back), projects_path

app/views/projects/index.html.slim
- content_for :main_title do
  div class='main-title-content'
    = t(:projects)
- if cfo_treasurer_case?
  = link_to new_project_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    = t(:new_project)
  br
  br

.table-responsive
  table.table.table-striped.table-bordered.table-hover#projects-table.no_scroll
    thead
      tr
        th
          = t(:project_name)
        th
          = t(:project_description)
        - if cfo_treasurer_case?
          th
          th
    tbody
      - @projects.each do | project |
        tr
          td
            = show_source(project.name, project_path(project.id))
          td
            = project.description
          - if cfo_treasurer_case?
            td
              = link_to t(:edit), edit_project_path(project)
            td
              = link_to t(:delete), project, method: :delete, data: { confirm: t(:delete_confirmation) }
script

  |$('#projects-table').dataTable({
  |        "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
  |        "iDisplayLength": 25,
  |        "order": [[0, 'desc']],
  |        "language": { "url": "#{root_url + '/assets/Russian.json'}" }
  |    }).animate({opacity: 1});

app/views/projects/new.html.slim
h1 = t(:new_project)

== render 'form'
br
= link_to t(:back), projects_path

app/views/projects/show.html.slim
- if not @project.blank?
  .panel.panel-default
    .panel-heading
      h3.panel-title
        b = t(:project)
    .panel-body
      dl
        dt
          = t(:project_name)
        br
        dd
          = @project.name
        br
        dt
          = t(:project_description)
        br
        dd
          = @project.description
        br
        = link_to t(:back), projects_path
        - if cfo_treasurer_case?
          = ' | '
          = link_to t(:edit), edit_project_path(@project)