config/routes.rb
Rails.application.routes.draw do
  resources :exchanges
  resources :incomes
  resources :records
  resources :expenditures
  resources :projects
  resources :events
  resources :orders do
    collection do
      get 'canceled'
      get 'executed'
    end
  end
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get 'order_file/:id', to: 'orders#download_file', as: 'order_file'
  delete 'order_file/:id', to: 'orders#delete_file'
  get 'record_file/:id', to: 'records#download_file', as: 'record_file'
  delete 'record_file/:id', to: 'records#delete_file'
  get 'exchange_file/:id', to: 'exchanges#download_file', as: 'exchange_file'
  delete 'exchange_file/:id', to: 'exchanges#delete_file'

  root to: 'orders#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Согласование наличия
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header.set-min-width
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Согласование", root_path, class: "navbar-brand"
          div class='header-title'
            = yield :main_title
          div class='exit-link'
            ul.nav.navbar-nav.desktop-only
              - if user_signed_in?
                li.current-user
                  = "( #{current_user.name}: #{current_user.role} )"
                li
                  = link_to t(:exit), "#myModal", data: { toggle: 'modal' }
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav.mobile-only
            li class="sidebar-brand"
              = link_to t(:current_orders), orders_path
            li class="sidebar-brand"
              = link_to t(:canceled_orders), canceled_orders_path
            li class="sidebar-brand"
              = link_to t(:executed_orders), executed_orders_path
            - if current_user && can_see_as_auditor_cfo_treasurer?
              li class="sidebar-brand"
                = link_to t(:projects), projects_path
              li class="sidebar-brand"
                = link_to t(:expenditures), expenditures_path
              li class="sidebar-brand"
                = link_to t(:income_sources), incomes_path
              li class="sidebar-brand"
                = link_to t(:journal), records_path
              li class="sidebar-brand"
                = link_to t(:exchanges), exchanges_path
            - if user_signed_in?
              li.active
                =link_to t(:exit), "#myModal", data: { toggle: 'modal' }

    .container-fluid
      div id="wrapper"
          div id="sidebar-wrapper"
            ul class="sidebar-nav"
              li class="sidebar-brand"
                = link_to t(:current_orders), orders_path
              li class="sidebar-brand"
                = link_to t(:canceled_orders), canceled_orders_path
              li class="sidebar-brand"
                = link_to t(:executed_orders), executed_orders_path
              - if current_user && can_see_as_auditor_cfo_treasurer?
                li class="sidebar-brand"
                  = link_to t(:journal), records_path
                li class="sidebar-brand"
                  = link_to t(:projects), projects_path, class: "small-sidebar-link set-top-border"
                  = link_to t(:expenditures), expenditures_path, class: "small-sidebar-link"
                  = link_to t(:income_sources), incomes_path, class: "small-sidebar-link"
                  = link_to t(:exchanges), exchanges_path, class: "small-sidebar-link"

          /Page Content
          div id="flash"
            - flash.each do |name, msg|
              - if name != "timedout"
                = content_tag :div, class: "alert alert-#{ name == 'error' ? "danger" : "success" } alert-dismissable", role: "alert" do
                  button.close type="button" data-dismiss="alert"
                    span aria-hidden="true"
                      | &times;
                    span.sr-only
                      | Close
                  - if msg.kind_of?(Array)
                    - msg.each do |x|
                      = x
                      br
                  - else
                    = msg

          div id="page-content-wrapper" class="full-width"
              div class="container-fluid"
                div class="row"
                    /a href="#menu-toggle" class="btn btn-default" id="menu-toggle"
                          | Toggle Menu
                    div class="col-lg-12"
                        = yield

            

  / Modal
  div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    div class="modal-dialog" role="document"
      div class="modal-content"
        div class="modal-header"
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true"
              |&times;
          h4 class="modal-title" id="myModalLabel"
            = t(:plutus)
        div class="modal-body text-center"
          h4 = t(:exit_confirmation)
        div class="modal-footer"
          = link_to t(:yep), destroy_user_session_path, method: :delete,       \
                                                        id: 'big_yep',         \
                                                        class: 'btn btn-primary'
          button type="button" class="btn btn-default" data-dismiss="modal" id='big_nope'
            = t(:nope)

  /<!-- Menu Toggle Script -->
  script
        | $("#menu-toggle").click(function(e) {
        |     e.preventDefault();
        |     $("#wrapper").toggleClass("toggled");
        | });
        | $(document).ready(function(){
        |  setTimeout(function(){
        |    $('#flash').hide();
        |  }, 7000);
        | });